In [1]:
import torch


c:\Users\SVT\anaconda3\envs\Pytorch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


- 텐서 생성 및 변환
    - 텐서는 파이토치의 가장 기본이 되는 데이터 구조
    - numpy 의 다차원배열과 비슷하며 GPU에서도 연산 가능

In [2]:
import torch
print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA version:", torch.version.cuda)
print("cuDNN version:", torch.backends.cudnn.version())


PyTorch version: 1.11.0
CUDA available: True
CUDA version: 11.3
cuDNN version: 8200


In [3]:
# 2차원 텐서 생성
torch.tensor([[1,2],
              [3,4]])

tensor([[1, 2],
        [3, 4]])

In [4]:
# GPU가 있다면
torch.tensor([[1,2],
              [3,4]], dtype=torch.float64)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [5]:
# GPU가 있다면 GPU상의 텐서를 GPU의 텐서로 변환 후 ndarray로 변환
temp = torch.tensor([[1,2], [3,4]], device = "cuda:0")
temp.to("cpu").numpy()

array([[1, 2],
       [3, 4]], dtype=int64)

- 텐서를 ndarray로 변환

In [ ]:
temp = torch.tensor([[1,2], [3,4]])

In [8]:
# ndarray로 변환
temp.numpy()

array([[1, 2],
       [3, 4]], dtype=int64)

In [9]:
# gpu가 있다면 gpu상의 텐서를 cpu의 텐서로 변환한 후 ndarray로 변환
temp = torch.tensor([[1, 2], [3, 4]], device = "cuda:0")
temp.to("cpu").numpy()

array([[1, 2],
       [3, 4]], dtype=int64)

- 텐서의 인덱스 조작
    - 텐서는 넘파이의 다치원배열과 유사하게 동작하기 때문에 배열처럼 인덱스를 바로 지정하거나 슬라이스 등을 사용할 수 있음

In [13]:
# 파이토치로 1차원 벡터 생성
temp = torch.FloatTensor([1,2,3,4,5,6,7])
temp

tensor([1., 2., 3., 4., 5., 6., 7.])

In [14]:
# 인덱스로 접근
temp[0], temp[1], temp[2]

(tensor(1.), tensor(2.), tensor(3.))

In [15]:
# 슬라이스로 접근
temp[2:5], temp[::2], temp[4:-1]

(tensor([3., 4., 5.]), tensor([1., 3., 5., 7.]), tensor([5., 6.]))

- 텐서 연산
    - 텐서는 넘파이의 다차원배열처럼 다양한 수학 연산이 가능하며, gpu를 사용하면 더 빨리 연산할 수 있음
    - 단, 텐서 간의 타입이 다르면 연산 불가
        - 예) FloatTensor(32비트의 부등 소수점)와 DoubleTensor(64비트의 부등 소수점) 간에 사칙 연산을 수행하면 오류 발생

In [ ]:
# 길이가 3인 벡터 생성
v = torch.tensor([1, 2, 3])
w = torch.tensor([4, 5, 6])

In [ ]:
# 길이가 같은 벡터 간 뺄셈 연산
print(w - v)

tensor([3, 3, 3])


- 텐서의 차원 조작
    - 텐서의 차원을 변경하는 명령어
        - view: 넘파이의 reshape와 유사
        - cat: 다른 길이의 텐서를 하나로 병합
        - transpose: 행렬의 전치 또는 차원의 순서 변경

In [ ]:
# 2 x 2 행렬 생성
temp = torch.tensor([
    [1, 2], [3, 4]
    ])

In [22]:
temp.shape

torch.Size([2, 2])

In [23]:
# 2 x 2 행렬을 4 x 1 행렬로 변환
temp.view(4, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [24]:
# 2x2 행렬을 1차원 벡터로 변형
temp.view(-1)

tensor([1, 2, 3, 4])

- -1 은 다른 차원으로부터 해당 값을 유추하겠다느 뜻

In [25]:
temp.view(1, -1)

tensor([[1, 2, 3, 4]])

In [26]:
temp.view(-1, 1)

tensor([[1],
        [2],
        [3],
        [4]])

- 데이터로더
    - torch.utils.data.DataLoader 는 학습에 사용될 데이터 전체를 보관했다가 모델 학습을 할 때 배치 크기만큼 데이터를 꺼내서 사용
    - 주의할 점은 미리 데이터를 잘라 놓는 것이 아니라 내부적으로 이터레이터에 포함된 인덱스를 이용하여 배치 크기만큼 데이터 반환

- 파이토치 데이터셋 사용
    - torchvision 은 파이토치에서 제공하는 데이터셋이 모여있는 패키지
    - 파이토치 데이터셋을 다운로드 받으려면 requests 라이브러리 설치 필요
        - HTTP 요청을 하기 위함

In [28]:
import torchvision.transforms as transforms
from torchvision.datasets import MNIST

In [30]:
# 평균이 0.5, 표준편차가 1.0이 되도록 데이터의 분포를 정규화
mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5), (1.0))
])

In [31]:
datapath = "./data/MNIST"

In [32]:
train_dataset = MNIST(datapath, transform = mnist_transform, train = True, download= True)
test_dataset = MNIST(datapath, transform = mnist_transform, train = False, download= True)

Failed to download (trying next):
HTTP Error 404: Not Found



9913344it [00:03, 2819799.26it/s]                             


Extracting ./data/MNIST\MNIST\raw\train-images-idx3-ubyte.gz to ./data/MNIST\MNIST\raw

Failed to download (trying next):
HTTP Error 404: Not Found



29696it [00:00, 165775.44it/s]                        


Extracting ./data/MNIST\MNIST\raw\train-labels-idx1-ubyte.gz to ./data/MNIST\MNIST\raw

Failed to download (trying next):
HTTP Error 404: Not Found



1649664it [00:01, 1278489.87it/s]                             


Extracting ./data/MNIST\MNIST\raw\t10k-images-idx3-ubyte.gz to ./data/MNIST\MNIST\raw

Failed to download (trying next):
HTTP Error 404: Not Found



5120it [00:00, 5121592.29it/s]          

Extracting ./data/MNIST\MNIST\raw\t10k-labels-idx1-ubyte.gz to ./data/MNIST\MNIST\raw



In [33]:
type(test_dataset)

torchvision.datasets.mnist.MNIST

In [40]:
# 확인용 코드
from torchvision import datasets, transforms

mnist_train = datasets.MNIST(root="./data", train = True, download=False, transform=transforms.ToTensor())
mnist_test = datasets.MNIST(root="./data", train = False, download=False, transform=transforms.ToTensor())

print("훈련 데이터 크기:", len(mnist_train))
print("테스트 데이터 크기:", len(mnist_test))
print("샘플 이미지 크기:", mnist_train[0][0].shape)

훈련 데이터 크기: 60000
테스트 데이터 크기: 10000
샘플 이미지 크기: torch.Size([1, 28, 28])


- 모델 정의
    - 파이토치에서 모델을 정의하기 위해서는 Module 을 상속한 클래스를 사용
        - layer : 모듈 또는 모듈을 구성하는 한 개의 계층
            - 예) 합성곱창, 선형계층 등
        - module : 한 개 이상의 계층이 모여서 구성된 것, 모듈이 모여 새로운 모듈을 만들 수도 있음

- nn.Module()을 상속하여 정의하는 방법
    - 파이토치에서 nn.Module을 상속받는 모델은 기본적으로 __init__() 과 forward() 함수를 포함
        - __init__() 에서는 모델에서 사용될 모듈, 활성화 함수 등을 정의
        - forward() 함수에서는 모델에서 실행되어야 하는 연산을 정의
    - nn.Sequential을 사용하면 __init__() 에서 사용할 네트워크 모델들을 정의해 줄 뿐만 아니라 forward() 함수의 모델에서 실행되어야 할 계산을 좀 더 가독성이 뛰어나게 코드로 작성할 수 있음

    - 또한, Sequential 객체에는 그 안에 포함된 각 모듈을 순차적으로 실행해 줌

In [41]:
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self):
        super().__init__()  # 부모 클래스의 생성자 먼저 실행해주고 자식 클래스 생성자 실행
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
            nn.ReLU(inplace=True),   # 활성화 함수
            # input으로 들어온 값 자체를 수정, 메모리 효율이 좋아지지만 input 값이 사라짐
            nn.MaxPool2d(2)
        )
        
        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2)
        )
        
        self.layer3 = nn.Sequential(
            nn.Linear(in_features=30*5*5, out_features=10, bias=True),
            nn.ReLU(inplace=True)
        )
    
    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        x = x.view(x.size(0), -1)  # Flatten the tensor
        x = self.layer3(x)
        return x


- __init__ : 생성자
- Conv2D : 2차원 형식, in_channels : 입력되는 채널, out_channels : 출력되는 채널, kernel_size : 가로 세로 크기 5
- bias : Y절편 쓰냐 안쓰냐
- 저 Linear가 Dense층이랑 같은 전결합층, dense layer

In [42]:
# 모델 객체 생성
model = MLP()

In [43]:
# 모델 구성 노드를 반환
list(model.children())

[Sequential(
   (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
   (1): ReLU(inplace=True)
   (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
 ),
 Sequential(
   (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
   (1): ReLU(inplace=True)
   (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
 ),
 Sequential(
   (0): Linear(in_features=750, out_features=10, bias=True)
   (1): ReLU(inplace=True)
 )]

- dilation : 커널 사이의 간격
- ceil_mode : 값의 올림처리(False), 내림처리(True)

In [44]:
# 모델의 네트워크에 대한 모든 노드를 반환
list(model.modules())

[MLP(
   (layer1): Sequential(
     (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
     (1): ReLU(inplace=True)
     (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
   )
   (layer2): Sequential(
     (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
     (1): ReLU(inplace=True)
     (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
   )
   (layer3): Sequential(
     (0): Linear(in_features=750, out_features=10, bias=True)
     (1): ReLU(inplace=True)
   )
 ),
 Sequential(
   (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
   (1): ReLU(inplace=True)
   (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
 ),
 Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1)),
 ReLU(inplace=True),
 MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False),
 Sequential(
   (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
   (1): ReLU(inplace=True)
   (2): MaxPool2d(kernel_size=2

- 함수로 신경망 정의

In [45]:
def MLP(in_features = 1, hidden_features = 20, out_features = 1):
    hidden = nn.Linear(in_features=in_features, out_features=hidden_features, bias=True)
    activation = nn.ReLU()
    output = nn.Linear(in_features=hidden_features, out_features=out_features, bias=True)
    net = nn.Sequential(hidden, activation, output)
    return net

In [46]:
mlp_model = MLP(in_features=10)